server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_master?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dhyadmin
    password: 1216459494
    platform: mysql
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

logging:
  level:
    root: info
    com.school.master: debug
